package view;

import model.Contacto;
import model.Conversacion;
import utils.ChatListRenderer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class Messenger extends JFrame {
    private JPanel pane;
    private JPanel panelOpciones;
    private JPanel panelPrincipal;
    private JButton btnNuevoContacto;
    private JPanel panelChats;
    private JPanel panelConversación;
    private JPanel panelEnviarMensaje;
    private JPanel panelSupChats;
    private JLabel lblChats;
    private JButton btnNuevoChat;
    private JPanel panelBuscarChat;
    private JLabel lblBuscarChat;
    private JTextField txtBuscarChat;
    private JPanel panelChatLista;
    private JPanel panelContactoInfo;
    private JPanel panelNombreContacto;
    private JPanel panelNombreContactoAux;
    private JLabel lblNombreMensaje;
    private JPanel panelPuertoIpChat;
    private JLabel lblIP;
    private JLabel lblPuerto;
    private JTextField txtMensaje;
    private JButton btnEnviar;
    private JTextArea txtAreaConversacion;
    private JList<Contacto> listChat;
    private DefaultListModel<Contacto> listModel;
    private JScrollPane scrollPane;
    private JButton btnLogin;

    public Messenger(String titulo) throws HeadlessException {
        super(titulo);
        this.setContentPane(this.pane);
        this.setSize(750, 600);
        this.setLocationRelativeTo(null);
        this.requestFocus();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);

        this.listModel = new DefaultListModel<>();
        this.listChat.setModel(this.listModel);
        this.listChat.setCellRenderer(new ChatListRenderer());
    }

    public void agregarContacto(Contacto c) {
        listModel.addElement(c);
    }

    public DefaultListModel<Contacto> getListModel() {
        return listModel;
    }

    public JButton getBtnNuevoContacto() {
        return btnNuevoContacto;
    }

    public void setBtnNuevoContacto(JButton btnNuevoContacto) {
        this.btnNuevoContacto = btnNuevoContacto;
    }

    public JLabel getLblChats() {
        return lblChats;
    }

    public void setLblChats(JLabel lblChats) {
        this.lblChats = lblChats;
    }

    public JButton getBtnNuevoChat() {
        return btnNuevoChat;
    }

    public void setBtnNuevoChat(JButton btnNuevoChat) {
        this.btnNuevoChat = btnNuevoChat;
    }

    public JLabel getLblBuscarChat() {
        return lblBuscarChat;
    }

    public void setLblBuscarChat(JLabel lblBuscarChat) {
        this.lblBuscarChat = lblBuscarChat;
    }

    public JTextField getTextField1() {
        return txtBuscarChat;
    }

    public void setTextField1(JTextField textField1) {
        this.txtBuscarChat = textField1;
    }

    public JLabel getLblNombreMensaje() {
        return lblNombreMensaje;
    }

    public void setLblNombreMensaje(JLabel lblNombreMensaje) {
        this.lblNombreMensaje = lblNombreMensaje;
    }

    public JLabel getLblIP() {
        return lblIP;
    }

    public void setLblIP(JLabel lblIP) {
        this.lblIP = lblIP;
    }

    public JLabel getLblPuerto() {
        return lblPuerto;
    }

    public void setLblPuerto(JLabel lblPuerto) {
        this.lblPuerto = lblPuerto;
    }

    public JTextField getTextField2() {
        return txtMensaje;
    }

    public void setTextField2(JTextField textField2) {
        this.txtMensaje = textField2;
    }

    public JButton getBtnEnviar() {
        return btnEnviar;
    }

    public void setBtnEnviar(JButton btnEnviar) {
        this.btnEnviar = btnEnviar;
    }

    public JTextArea getTxtAreaConversacion() {
        return txtAreaConversacion;
    }

    public void setTxtAreaConversacion(JTextArea txtAreaConversacion) {
        this.txtAreaConversacion = txtAreaConversacion;
    }

    public JList<Contacto> getListChat() {
        return listChat;
    }

    public void setListChat(JList<Contacto> listChat) {
        this.listChat = listChat;
    }

    public JPanel getPanelContactoInfo() {
        return panelContactoInfo;
    }

    public void setPanelContactoInfo(JPanel panelContactoInfo) {
        this.panelContactoInfo = panelContactoInfo;
    }

    public JTextField getTxtBuscarChat() {
        return txtBuscarChat;
    }

    public void setTxtBuscarChat(JTextField txtBuscarChat) {
        this.txtBuscarChat = txtBuscarChat;
    }

    public JTextField getTxtMensaje() {
        return txtMensaje;
    }

    public void setTxtMensaje(JTextField txtMensaje) {
        this.txtMensaje = txtMensaje;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pane = new JPanel();
        pane.setLayout(new BorderLayout(0, 0));
        pane.setMinimumSize(new Dimension(400, 400));
        pane.setPreferredSize(new Dimension(750, 600));
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new BorderLayout(0, 0));
        panelPrincipal.setPreferredSize(new Dimension(640, 600));
        pane.add(panelPrincipal, BorderLayout.CENTER);
        panelChats = new JPanel();
        panelChats.setLayout(new BorderLayout(0, 0));
        panelPrincipal.add(panelChats, BorderLayout.WEST);
        panelSupChats = new JPanel();
        panelSupChats.setLayout(new BorderLayout(0, 0));
        panelChats.add(panelSupChats, BorderLayout.NORTH);
        lblChats = new JLabel();
        lblChats.setText("Chats");
        panelSupChats.add(lblChats, BorderLayout.WEST);
        btnNuevoChat = new JButton();
        btnNuevoChat.setEnabled(false);
        btnNuevoChat.setMargin(new Insets(5, 5, 5, 5));
        btnNuevoChat.setText("Nuevo Chat");
        panelSupChats.add(btnNuevoChat, BorderLayout.EAST);
        panelBuscarChat = new JPanel();
        panelBuscarChat.setLayout(new BorderLayout(0, 0));
        panelSupChats.add(panelBuscarChat, BorderLayout.SOUTH);
        lblBuscarChat = new JLabel();
        lblBuscarChat.setText("Buscar chat");
        panelBuscarChat.add(lblBuscarChat, BorderLayout.NORTH);
        txtBuscarChat = new JTextField();
        panelBuscarChat.add(txtBuscarChat, BorderLayout.SOUTH);
        panelChatLista = new JPanel();
        panelChatLista.setLayout(new BorderLayout(0, 0));
        panelChatLista.setPreferredSize(new Dimension(220, 515));
        panelChats.add(panelChatLista, BorderLayout.CENTER);
        scrollPane = new JScrollPane();
        scrollPane.setHorizontalScrollBarPolicy(31);
        scrollPane.setOpaque(true);
        scrollPane.setPreferredSize(new Dimension(200, 515));
        panelChatLista.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        listChat = new JList();
        listChat.setFixedCellHeight(60);
        listChat.setFixedCellWidth(-1);
        listChat.setMinimumSize(new Dimension(150, 728));
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        listChat.setModel(defaultListModel1);
        listChat.setPreferredSize(new Dimension(200, 515));
        listChat.setSelectionMode(0);
        listChat.setVisibleRowCount(8);
        scrollPane.setViewportView(listChat);
        panelConversación = new JPanel();
        panelConversación.setLayout(new BorderLayout(0, 0));
        panelConversación.setPreferredSize(new Dimension(280, 62));
        panelPrincipal.add(panelConversación, BorderLayout.CENTER);
        panelEnviarMensaje = new JPanel();
        panelEnviarMensaje.setLayout(new BorderLayout(0, 0));
        panelConversación.add(panelEnviarMensaje, BorderLayout.SOUTH);
        btnEnviar = new JButton();
        btnEnviar.setEnabled(false);
        btnEnviar.setText("Enviar");
        panelEnviarMensaje.add(btnEnviar, BorderLayout.EAST);
        txtMensaje = new JTextField();
        panelEnviarMensaje.add(txtMensaje, BorderLayout.CENTER);
        panelContactoInfo = new JPanel();
        panelContactoInfo.setLayout(new BorderLayout(0, 0));
        panelContactoInfo.setPreferredSize(new Dimension(0, 85));
        panelContactoInfo.setVisible(false);
        panelConversación.add(panelContactoInfo, BorderLayout.NORTH);
        panelNombreContacto = new JPanel();
        panelNombreContacto.setLayout(new BorderLayout(0, 0));
        panelNombreContacto.setPreferredSize(new Dimension(168, 85));
        panelContactoInfo.add(panelNombreContacto, BorderLayout.CENTER);
        panelNombreContactoAux = new JPanel();
        panelNombreContactoAux.setLayout(new BorderLayout(0, 0));
        panelNombreContactoAux.setMinimumSize(new Dimension(168, 64));
        panelNombreContactoAux.setPreferredSize(new Dimension(168, 64));
        panelNombreContacto.add(panelNombreContactoAux, BorderLayout.CENTER);
        lblNombreMensaje = new JLabel();
        lblNombreMensaje.setText("Nombre del contacto");
        panelNombreContactoAux.add(lblNombreMensaje, BorderLayout.CENTER);
        panelPuertoIpChat = new JPanel();
        panelPuertoIpChat.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panelNombreContactoAux.add(panelPuertoIpChat, BorderLayout.SOUTH);
        lblIP = new JLabel();
        lblIP.setText("IP:localhost");
        panelPuertoIpChat.add(lblIP);
        lblPuerto = new JLabel();
        lblPuerto.setText("Puerto:9999");
        panelPuertoIpChat.add(lblPuerto);
        final JScrollPane scrollPane1 = new JScrollPane();
        panelConversación.add(scrollPane1, BorderLayout.CENTER);
        txtAreaConversacion = new JTextArea();
        txtAreaConversacion.setEditable(false);
        txtAreaConversacion.setFocusable(false);
        txtAreaConversacion.setLineWrap(true);
        txtAreaConversacion.setMargin(new Insets(5, 5, 5, 5));
        txtAreaConversacion.setText("");
        txtAreaConversacion.setWrapStyleWord(true);
        scrollPane1.setViewportView(txtAreaConversacion);
        panelOpciones = new JPanel();
        panelOpciones.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpciones.setMaximumSize(new Dimension(300, 32767));
        panelOpciones.setMinimumSize(new Dimension(80, 44));
        panelOpciones.setPreferredSize(new Dimension(110, 44));
        panelOpciones.putClientProperty("html.disable", Boolean.FALSE);
        pane.add(panelOpciones, BorderLayout.WEST);
        btnLogin = new JButton();
        btnLogin.setMargin(new Insets(5, 5, 5, 5));
        btnLogin.setText("Iniciar Sesión");
        panelOpciones.add(btnLogin);
        btnNuevoContacto = new JButton();
        btnNuevoContacto.setActionCommand("nuevoContacto");
        btnNuevoContacto.setAutoscrolls(false);
        btnNuevoContacto.setEnabled(false);
        btnNuevoContacto.setHorizontalTextPosition(11);
        btnNuevoContacto.setLabel("<html><center>Nuevo<br>Contacto</center></html>");
        btnNuevoContacto.setMargin(new Insets(5, 5, 5, 5));
        btnNuevoContacto.setMinimumSize(new Dimension(80, 34));
        btnNuevoContacto.setPreferredSize(new Dimension(100, 34));
        btnNuevoContacto.setText("<html><center>Nuevo<br>Contacto</center></html>");
        panelOpciones.add(btnNuevoContacto);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pane;
    }

}
