package view;

import controller.NuevoChatController;
import interfaces.IVista;
import model.Contacto;

import javax.swing.*;
import java.awt.*;

public class NuevoChat extends JDialog implements IVista<NuevoChatController> {
    private JPanel pane;
    private JList<Contacto> list1;
    private JTextField txtBuscar;
    private JPanel paneBuscar;
    private JLabel lblBuscar;
    private DefaultListModel<Contacto> listModel;
    private NuevoChatController controlador;
    private Frame main;

    public NuevoChat(Frame main) throws HeadlessException {
        super(main);
        this.main = main;
        this.setContentPane(this.pane);
        this.setTitle("Nuevo Chat");
        this.setLocationRelativeTo(null);
        this.requestFocus();
        this.setVisible(true);

        this.listModel = new DefaultListModel<>();
        this.list1.setModel(this.listModel);
    }

    public JList<Contacto> getList1() {
        return list1;
    }

    public void setList1(JList<Contacto> list1) {
        this.list1 = list1;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

    public JLabel getLblBuscar() {
        return lblBuscar;
    }

    public void setLblBuscar(JLabel lblBuscar) {
        this.lblBuscar = lblBuscar;
    }

    public void display() {
        this.pack();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(main);
        this.setVisible(true);
    }

    public void agregarContacto(Contacto c) {
        listModel.addElement(c);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pane = new JPanel();
        pane.setLayout(new BorderLayout(0, 0));
        pane.setMinimumSize(new Dimension(300, 250));
        pane.setPreferredSize(new Dimension(300, 525));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        pane.add(panel1, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        list1 = new JList();
        list1.setFixedCellHeight(60);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("JUAN ANTORIO NORIO¨PES");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        defaultListModel1.addElement("a");
        list1.setModel(defaultListModel1);
        list1.setSelectionMode(0);
        scrollPane1.setViewportView(list1);
        paneBuscar = new JPanel();
        paneBuscar.setLayout(new BorderLayout(0, 0));
        paneBuscar.setMinimumSize(new Dimension(49, 60));
        paneBuscar.setPreferredSize(new Dimension(49, 60));
        panel1.add(paneBuscar, BorderLayout.NORTH);
        txtBuscar = new JTextField();
        txtBuscar.setBackground(new Color(-526345));
        txtBuscar.setForeground(new Color(-16777216));
        paneBuscar.add(txtBuscar, BorderLayout.SOUTH);
        lblBuscar = new JLabel();
        lblBuscar.setText("Buscar");
        paneBuscar.add(lblBuscar, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pane;
    }

    @Override
    public void setControlador(NuevoChatController controlador) {
        this.controlador = controlador;
    }
}
