package model;

public enum TipoSolicitud {
    OBTENER_DIRECTORIO,
    ENVIAR_MENSAJE,
    RECIBIR_MENSAJE,
    REGISTRARSE,
    INICIAR_SESION,
    CONECTARSE_SERVIDOR,
    CERRAR_SESION,
    AGREGAR_CONTACTO,
    ELIMINAR_CONTACTO,
    OBTENER_CONVERSACIONES,
    CONEXION_PERDIDA,
    ACTUALIZAR_USUARIO
}

